AppBundle\Entity\Location:
  exclusion_policy: ALL
  properties:
      id:
          expose: true
      status:
          expose: false
      createDate:
          expose: false
      createUser:
          expose: false
      writeDate:
          expose: false
      writeUser:
          expose: false
      name:
          expose: true
      address:
          expose: true