<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnualCostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnualCostRepository extends EntityRepository
{

    public function findByLocation(Location $location){
        $queryString = "select e from AppBundle:AnnualCost e
              where e.status = :status and e.location = :location
              order by e.year asc ";

        $query = $this->getEntityManager()->createQuery($queryString);
        $query->setParameter("status",true);
        $query->setParameter("location", $location);

        return $query->getResult();

    }

}
