<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AssignedCollectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssignedCollectorRepository extends EntityRepository
{

    public function getEM(){
        return $this->getEntityManager();
    }

    public function findCurrentCollector($collectorCode){
        $query = $this->_em->createQuery('
            SELECT ac from AppBundle:AssignedCollector ac
            inner join ac.collector c
            where c.status = :status
            and c.code=:code')
            ->setParameter('status', true)
            ->setParameter('code', $collectorCode);
        if($query->getResult() != null){
            return $query->getResult()[0];
        }
        return null;
    }

    public function findByEnergyPoint(EnergyPoint $energyPoint){
        $queryString = "select e from AppBundle:AssignedCollector e
              where e.energyPoint = :energypoint
              order by e.id asc ";

        $query = $this->getEntityManager()->createQuery($queryString);
        $query->setParameter("energypoint", $energyPoint);

        return $query->getResult();

    }

}
