<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EnergyPointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnergyPointRepository extends EntityRepository
{

    public function getEM(){
        return $this->getEntityManager();
    }

    public function countAll($code){

        $queryString = "select count(l) from AppBundle:EnergyPoint l where l.status = :status ";
        if($code!=null && $code!=''){
            $queryString = $queryString." and l.code like :code ";
        }

        $query = $this->getEM()->createQuery($queryString)
            ->setParameter("status",true);

        if($code!=null && $code != ""){
            $query->setParameter("code","%".$code."%");
        }

        return $query->getSingleScalarResult();
    }


    public function findByPage($code, $offset, $limit){

        $queryString = "select l from AppBundle:EnergyPoint l where l.status = :status";
        if($code!=null && $code!=''){
            $queryString = $queryString." and l.code like :code ";
        }

        $queryString = $queryString." order by l.code asc ";

        $query = $this->getEM()->createQuery($queryString)
            ->setFirstResult($offset)
            ->setMaxResults($limit);

        $query->setParameter("status",true);

        if($code!=null && $code != ""){
            $query->setParameter("code","%".$code."%");
        }

        return $query->getResult();

    }

    public function saveOrUpdate(EnergyPoint $energyPoint){
        $this->getEntityManager()->persist($energyPoint);
        $this->getEntityManager()->flush();
    }


    public function findByLocation(Location $location){
        $queryString = "select e from AppBundle:EnergyPoint e
              where e.status = :status and e.location = :location
              order by e.code asc ";

        $query = $this->getEntityManager()->createQuery($queryString);
        $query->setParameter("status",true);
        $query->setParameter("location", $location);

        return $query->getResult();

    }
}
