<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends EntityRepository
{
    public function getEM(){
        return $this->getEntityManager();
    }

    public function countAll($name){

        $queryString = "select count(l) from AppBundle:Location l where l.status = :status ";
        if($name!=null && $name!=''){
            $queryString = $queryString." and l.name like :name ";
        }

        $query = $this->getEM()->createQuery($queryString)
            ->setParameter("status",true);

        if($name!=null && $name != ""){
            $query->setParameter("name","%".$name."%");
        }

        return $query->getSingleScalarResult();
    }

    public function findAll(){
        $query = $this->getEM()->createQuery("select l from AppBundle:Location l where l.status = :status")
            ->setParameter("status", true);
        return $query->getResult();
    }

    public function findByPage($name, $offset, $limit){

        $queryString = "select l from AppBundle:Location l where l.status = :status";
        if($name!=null && $name!=''){
            $queryString = $queryString." and l.name like :name ";
        }

        $queryString = $queryString." order by l.name asc ";

        $query = $this->getEM()->createQuery($queryString)
            ->setFirstResult($offset)
            ->setMaxResults($limit);

        $query->setParameter("status",true);

        if($name!=null && $name != ""){
            $query->setParameter("name","%".$name."%");
        }

        return $query->getResult();

    }

    public function saveOrUpdate(Location $location){
        $this->getEntityManager()->persist($location);
        $this->getEntityManager()->flush();
    }
}
