<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SignalGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignalGroupRepository extends EntityRepository
{

    public function getEM(){
        return $this->getEntityManager();
    }

    public function saveOrUpdate(SignalGroup $signalGroup){
        $this->getEntityManager()->persist($signalGroup);
        $this->getEntityManager()->flush();
    }
}
