<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SignalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignalRepository extends EntityRepository
{

    public function getEM(){
        return $this->getEntityManager();
    }

    public function saveOrUpdate(Signal $signal){
        $this->getEntityManager()->persist($signal);
        $this->getEntityManager()->flush();
    }

    public function countByEnergyPoint(EnergyPoint $energyPoint){
        $queryString = "select count(s) from AppBundle:Signal s where s.status = :status and s.energyPoint = :point ";
        $query = $this->getEM()->createQuery($queryString)
            ->setParameter("status",true)->setParameter("point", $energyPoint);
        return $query->getSingleScalarResult();
    }
}
